// ** BismiIllah Ar-Rahmaan Ar-Raheem ** \\

using NoorSound.Models;
using Supabase;

namespace NoorSound.Services
{
    public class AuthService : IAuthService
    {
        private readonly Client _supabaseClient;


        public AuthService(Supabase.Client supabaseClient)
        {
            _supabaseClient = supabaseClient;
        }


        public async Task SignUp(string email, string password, string adminName)
        { 
            // In Shaa Allah ta'ala, this make a new user
            var response = await _supabaseClient.Auth.SignUp(email, password);


            if (response == null || response.User == null || string.IsNullOrWhiteSpace(response.User.Id))
                throw new Exception("Signup failed: no valid user returned"); //In Shaa Allah ta'ala, this exception is to developer. (users can't see it)
            
            var adminInsert = new AdminInsert
            {
                Id = response.User.Id,
                Name = adminName
            };

            
            await _supabaseClient
               .From<AdminInsert>() 
               .Insert(adminInsert);

        }

        public async Task LogIn(string email, string password)
        {
            //if an exception is thrown, viewModel will In Shaa Allah ta'ala catch it. 
            await _supabaseClient.Auth.SignIn(email, password); 
        }

        public async Task SignOut()
        {
            await _supabaseClient.Auth.SignOut();
        }

        public Supabase.Gotrue.User CurrentUser()
        {
            // In Shaa Allah ta'ala, this return the current user, if there is no user, it will return null 
            // (almost autogenerated comment. Don't know if the explanation it's correct) 
            return _supabaseClient.Auth.CurrentUser;
        }


        public string CurrentUserId()
        {
            // In Shaa Allah ta'ala, this return the current user id, if there is no user, it will return null 
            // (almost autogenerated comment. Don't know if the explanation it's correct) 
            return _supabaseClient.Auth.CurrentUser?.Id; 
        }

    }
}
