// ** BismiIllah Ar-Rahmaan Ar-Raheem ** \\

using NoorSound.Models;
using Supabase;

namespace NoorSound.Services
{
    public class AuthService : IAuthService
    {
        private readonly Client _supabaseClient;


        public AuthService(Supabase.Client supabaseClient)
        {
            _supabaseClient = supabaseClient;
        }


        public async Task SignUp(string email, string password, string adminName)
        {
            if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password) || string.IsNullOrEmpty(adminName))
            {
                await Shell.Current.DisplayAlertAsync("Error", "Remember to fill in all fields", "OK");
                return;
            }

            
            // In Shaa Allah, this make a new user
            var response = await _supabaseClient.Auth.SignUp(email, password);

            if (response == null)
                throw new Exception("User could not be made");

            var user = response.User;

            if (user == null || user.Id == null)
                throw new Exception("User could not be made");


            var admin = new Admin
            {
                Id = user.Id,
                Name = adminName
            };

            // In Shaa Allah, the new user will be inserted to the Admin table
            await _supabaseClient
               .From<Admin>()
               .Insert(admin);


        }

        public async Task SignIn(string email, string password)
        {
            try
            {
                await _supabaseClient.Auth.SignIn(email, password);
            }
            catch 
            {
                await Shell.Current.DisplayAlertAsync("Error", " Invalid email or password, did you sign up? ", "OK");
            }
            
        }

        public async Task SignOut()
        {
            await _supabaseClient.Auth.SignOut();
        }

        public string CurrentUserId()
        {
            // In Shaa Allah, this return the current user id, if there is no user, it will return null 
            // (almost autogenerated comment. Don't know if it's correct) 
            return _supabaseClient.Auth.CurrentUser?.Id; 
        }


    }
}
