// ** BismiIllah Ar-Rahmaan Ar-Raheem ** \\

using NoorSound.Models;
using Supabase;

namespace NoorSound.Services
{
    public class AuthService : IAuthService
    {
        private readonly Client _supabaseClient;


        public AuthService(Supabase.Client supabaseClient)
        {
            _supabaseClient = supabaseClient;
        }


        public async Task SignUp(string email, string password, string adminName)
        {
            if (string.IsNullOrWhiteSpace(email) || string.IsNullOrWhiteSpace(password) || string.IsNullOrWhiteSpace(adminName))
            {
                throw new Exception("All fields must be filled");
            }

            
            // In Shaa Allah, this make a new user
            var response = await _supabaseClient.Auth.SignUp(email, password);


            if (response == null || response.User == null || string.IsNullOrWhiteSpace(response.User.Id))
                throw new Exception("Signup failed: no valid user returned");
            
            var adminInsert = new AdminInsert
            {
                Id = response.User.Id,
                Name = adminName
            };

            
            await _supabaseClient
               .From<AdminInsert>() 
               .Insert(adminInsert);


        }

        public async Task LogIn(string email, string password)
        {

            if (string.IsNullOrWhiteSpace(email) || string.IsNullOrWhiteSpace(password))
            {
                throw new Exception("All fields must be filled");
            }

            await _supabaseClient.Auth.SignIn(email, password); //if an exception is thrown, viewModel will In Shaa Allah ta'ala catch it. 
        }

        public async Task SignOut()
        {
            await _supabaseClient.Auth.SignOut();
        }

        public Supabase.Gotrue.User CurrentUser()
        {
            // In Shaa Allah, this return the current user id, if there is no user, it will return null 
            // (almost autogenerated comment. Don't know if it's correct) 
            return _supabaseClient.Auth.CurrentUser;
        }


        public string CurrentUserId()
        {
            // In Shaa Allah, this return the current user id, if there is no user, it will return null 
            // (almost autogenerated comment. Don't know if it's correct) 
            return _supabaseClient.Auth.CurrentUser?.Id; 
        }

    }
}
